# Generated by Django 3.1.1 on 2021-04-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouch.voucher')),
            ],
        ),
    ]
