# Generated by Django 3.1.1 on 2021-04-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouch', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mob',
        ),
    ]
